# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: linode

provisioner:
  name: salt_solo
  formula: ruby
  state_top:
    base:
      "*":
        - ruby

platforms:
  - name: debian_jessie

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        ruby.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - ruby
